import numpy as np
from keras.preprocessing import sequence


def model_from_maxlen(model):
    conf = model.get_config()
    # if type(conf) is list:
    conf = [i for i in conf["layers"] if i['class_name'] == 'Embedding'][0]['config']

    # else:
    #     conf = [i for i in conf["layers"]
    #             if i['class_name'] == 'Embedding'][0]['config']
    maxlen = conf.get('input_length', 82)

    return maxlen

def expanded_node(model,state_position,charset,seed):
    """
    Generate character of current node.
    
    Parameters
    -----------
    model : model object
        initialized smiles string
    state_position : list
        char list of input smiles
    charset : list
        charset for generating smiles string 
        
    Returns
    -----------
    children_indexes : list
        list of character indexes that next current node
    """
    maxlen = model_from_maxlen(model)
    children_indexes =[]
    smiles_characters =[]
    smiles_characters.extend(state_position)
    smiles_indexes_old =[]
    for j in range(len(smiles_characters)):
        smiles_indexes_old.append(charset.index(smiles_characters[j]))

    smiles_indexes=smiles_indexes_old

    x=np.reshape(smiles_indexes,(1,len(smiles_indexes)))
    x_pad= sequence.pad_sequences(x, maxlen=maxlen, dtype='int32',
        padding='post', truncating='pre', value=0.)

    predictions=model_predict(model, x_pad)
    preds=np.asarray(predictions[0][len(smiles_indexes)-1]).astype('float64')
    preds = np.log(preds) / 1.0
    preds = np.exp(preds) / np.sum(np.exp(preds))
    for i in range(30):
        next_probas = np.random.multinomial(1, preds, 1)
        next_int=np.argmax(next_probas)
        children_indexes.append(next_int)

    children_indexes=list(set(children_indexes))
    #print(children_indexes)

    return children_indexes


def index_to_char(children_indexes, charset):
    """
    convert index list to char list
    
    Parameters
    -----------
    children_indexes : list
        list of indexes that next current node
    charset : list
        charset for generating smiles string 
        
    Returns
    -----------
    children_characters : list
        list of characters that next current node
    """
    children_characters=[]
    for i in range(len(children_indexes)):
        children_characters.append(charset[children_indexes[i]])

    #print(children_characters)

    return children_characters

def chem_kn_simulation_single(model, state_position, charset, children_character, seed):
    """
    Do playout using smiles that concat with state_position and children_character.
    
    Parameters
    -----------
    model : model object
        RNN model
    state_position : list
        char list of input smiles
    charset : list
        charset for generating smiles string 
    children_character : char
        character that next current node
        
    Returns
    -----------
    total_generated : list
        list of valid smiles that generated by playout(size = 1)
    """
    maxlen = model_from_maxlen(model)
    end="\n"
    smiles_characters=[]
    smiles_characters.extend(state_position)
    smiles_characters.append(children_character)
    total_generated=[]
    smiles_indexes_old=[]
    for j in range(len(smiles_characters)):
        smiles_indexes_old.append(charset.index(smiles_characters[j]))

    smiles_indexes=smiles_indexes_old

    x=np.reshape(smiles_indexes,(1,len(smiles_indexes)))
    x_pad= sequence.pad_sequences(x, maxlen=maxlen, dtype='int32',
        padding='post', truncating='pre', value=0.)
    while not smiles_indexes[-1] == charset.index(end):
        predictions=model_predict(model, x_pad)
        #print "shape of RNN",predictions.shape
        preds=np.asarray(predictions[0][len(smiles_indexes)-1]).astype('float64')
        preds = np.log(preds) / 1.0
        preds = np.exp(preds) / np.sum(np.exp(preds))
        next_probas = np.random.multinomial(1, preds, 1)
        next_int=np.argmax(next_probas)
        a=predictions[0][len(smiles_indexes)-1]
        next_int_test=sorted(list(range(len(a))), key=lambda i: a[i])[-10:]
        smiles_indexes.append(next_int)
        x=np.reshape(smiles_indexes,(1,len(smiles_indexes)))
        x_pad = sequence.pad_sequences(x,
                                       maxlen=maxlen,
                                       dtype='int32',
                                       padding='post',
                                       truncating='pre',
                                       value=0.)
        if len(smiles_indexes) > maxlen:
            break
    total_generated.append(smiles_indexes)

    return total_generated


def predict_smile(all_possible_smiles, charset):
    """
    delete '&' from each smiles characters
    
    Parameters
    -----------
    all_possible_smiles : list
        
    charset : list
        charset for generating smiles string 
        
    Returns
    -----------
    new_compound : list
        list of smiles characters that next current node
    """
    new_compound=[]
    for i in range(len(all_possible_smiles)):
        total_generated=all_possible_smiles[i]

        generate_smile=[]

        for j in range(len(total_generated)-1):
            generate_smile.append(charset[total_generated[j]])
        generate_smile.remove("&")
        new_compound.append(generate_smile)

    return new_compound


def make_input_smile(generate_smile):
    """
    convert "smiles characters list" to "smiles string list"
    
    Parameters
    -----------
    generate_smile : list
        list of smiles characters that next current node
        
    Returns
    -----------
    new_compound : list
        list of smiles string that next current node
    """
    new_compound=[]
    for i in range(len(generate_smile)):
        middle=[]
        for j in range(len(generate_smile[i])):
            middle.append(generate_smile[i][j])
        com=''.join(middle)
        new_compound.append(com)

    return new_compound


debug_predict = False
predict_count = 0
total_time = 0.
import time
def model_predict(model,x_pad):
    global predict_count
    global total_time
    if debug_predict == False:
        return model.predict(x_pad)

    n = 10
    start = time.perf_counter()
    for i in range(n):
        predictions = model.predict(x_pad)
    total_time += (time.perf_counter() - start) / n
    predict_count += 1
    return predictions

def get_predict_time():
    global predict_count
    global total_time
    if debug_predict:
        return total_time / predict_count
    else:
        return None
